### ISSUE TITLE
For Ember 4 compatibility, add "for" and "since" attributes to options in all calls to deprecate()

### ISSUE THREAD

**Issue by camario25** [ember-lifeline/ember-lifeline#1121]
So now Ember 4 breaks if there are not "for" and "since" attributes in the options of a call to the deprecate function. The deprecation warning will not even show, we'll get an Ember error.

It happened to me with runDisposables using Ember 4 and Ember-lifeline v 6.0.2

I was able to go to ember-lifeline github and it gave me a clue that this was the issue. Funny thing is I can't find a deprecate call for runDisposables I'm wondering if it's in the the mixins?

Please update All your calls to deprecate(), I see some have the "for" and "since" attributes and some do not.  Thank you!

This is from ember deprecations docs:
https://deprecations.emberjs.com/v3.x

I've also attached a screenshot.
![Screen Shot 2022-05-17 at 3 48 23 PM](https://user-images.githubusercontent.com/33880128/168924942-18c1036a-9264-4b00-8a98-76216a73422c.png)

**Comment by scalvert** [comment]
Hey @camario25, the latest version, which is currently in beta, no longer has any deprecate calls. Please feel free to update to that to try it out!
