### ISSUE TITLE
Why block calls to tasks on a destroyed object when you could return early?

### ISSUE THREAD

**Issue by KnownSubset** [ember-lifeline/ember-lifeline#130]
The *README.md* states that this addon "should provide a simple developer experience that allows engineers to focus on the business domain, and think less about the weird parts of working in a long-lived app."  However, when integrating the addon into secondstreet/ember-material-components-web/pull/71 I found I had to check for `object.isDestroyed` before calling the ember-lifeline's scheduling tasks.  

I would prefer for ember-lifeline to *not* `throw` when the object passed in `isDestroyed`.  What it should do can be up for discussion.

**Comment by rwjblue** [comment]
Can you share a more isolated reproduction here? That PR is fairly large, and I'm not sure specifically which parts you are referring to.

**Comment by BryanCrotaz** [comment]
See #168 for my take on the same issue
