### ISSUE TITLE
scheduleTask fails if target object is already destroyed

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-lifeline/ember-lifeline#168]
Thoughts - scheduleTask is intended to save the dev from the dreaded isDestroying checks.

Consider:

```
<img onerror={{action imgError}} />
...
imgError() {
  scheduleTask(this, 'actions', () => {
    this.broken = true;
  });
}
```
If the component is torn down before the dom event fires, this can cause
```
Assertion Failed: Called `scheduleTask` on destroyed object: <dummy@component:my-image::ember770>
```

As `scheduleTask` is supposed to protect the dev from this on the event firing, maybe it should also check when `scheduleTask` is called and just exit silently?

**Comment by scalvert** [comment]
Right now it asserts.

https://github.com/ember-lifeline/ember-lifeline/blob/master/addon/run-task.ts#L130

This has been the functionality for a while. I believe this is behaving as intended, but I'm open to a counter argument.

@rwjblue - thoughts?

**Comment by BryanCrotaz** [comment]
My opinion would be that the assert should be replaced with pseudo code
```
if (destroying) return;
```

**Comment by scalvert** [comment]
I'd like to consult @rwjblue on what he thinks here. He usually has opinions...
