### ISSUE TITLE
pollTask in service degrades acceptance test performance

### ISSUE THREAD

**Issue by code0100fun** [ember-lifeline/ember-lifeline#22]
I noticed an increase in total test time when I used `pollTask` in a service.

```
interval =  100 ms -> 33 seconds
interval =  500 ms -> 53 seconds
interval = 1000 ms -> 82 seconds
```

This is the relevant service code:

```js
// app/services/clock.js
init() {
  this._super(...arguments);
  this.pollTask('update', 'clock#update');
},
update(next) {
  let serverTime = this.get('serverTime');
  if (serverTime) {
    // ...
    this.set('serverTime', new Date(localMillis - totalOffset));
  }
  this.runTask(next, 500); // <-- 500 ms interval
},
```

and the one test that actually uses `pollTaskFor` is something like:

```js
// tests/acceptance/clock-test.js
const mockTimeService = Service.extend({
  now() {
    return clientTime;
  },
  offset() {
    return clientOffset;
  }
});

//...

await login.visit();

await assert.equal(clock.date, '16 Mar 2017', 'clock shows date');
await assert.equal(clock.time, '6:30:20 pm', 'clock shows time');
await assert.equal(clock.timezone, 'Pacific', 'clock shows timezone');

clientTime = moment('2018-04-17T19:35:25.100', 'YYYY-MM-DDTHH:mm:ss.SSS').toDate();
await pollTaskFor('clock#update');

await assert.equal(clock.date, '17 Apr 2018', 'updated clock shows date');
await assert.equal(clock.time, '3:35:25 pm', 'updated clock shows time');
await assert.equal(clock.timezone, 'Pacific', 'updated clock shows timezone');
```

The test really doesn't effect anything, I just think the `async`/`await` combined with the `pollTaskFor` is just super nice looking 😁 thanks for the awesome work!

One thing that may be causing this is that I'm mixing this into a service, not a component. I tried debugging this a bit and it seems like `runTask` is the culprit. Without it the test suite drops back down to 29 seconds.

I profiled when the polling started and when the timers where cleared and this is what I got (with an interval of 1000 ms):

```
pollTask 851 ms
runTask 853 ms
willDestroy 1901 ms
```

It may be that the services `willDestroy` hook is not called until all tasks in the run loop have finished but I'm not very familiar with the inner workings of the run loop.

As a temporary fix I'm setting the interval to 0 in test:

```js
let interval = 500;
if (Ember.testing) {
  interval = 0;
}
this.runTask(next, interval);
```

**Comment by rwjblue** [comment]
Hmm. Well, the runTask (of 500ms) is explicitly specifying to the test to wait for 500ms. This seems completely expected. In this circumstance before, I have generally imported the timer durations from config/environment and defined separate durations for test vs prod/dev.

It is totally possible (and something that I wanted to start experimenting with) to "fast forward timers" while testing. The idea would be that timers would be guaranteed ordering wise, but would not respect the exact time delay specified.

**Comment by code0100fun** [comment]
Ok I guess I was interpreting the docs wrong:

> In testing, the `updateTime` method would execute initially during the components instantiation (just like in development and production environments), but would not automatically start polling. This allows tests that are not related to the polling behavior to continue uninterrupted. To test the actual polling functionality, use the provided `pollTaskFor` helper

I was thinking that in test the `runTask` combined with `pollTask` would only execute the `tick` when `pollTaskFor` was called.

I think shortening the timers in test automatically is a good idea. Although yeah, the order would need to be preserved. For now I'll move the configuration into the config.

**Comment by rwjblue** [comment]
> I was thinking that in test the runTask combined with pollTask would only execute the tick when pollTaskFor was called.

OH! Yes, I see what you mean here.  Reopening so I don't forget to dig into it...

**Comment by scalvert** [comment]
Just doing a bit of cleanup on issues in this repo. If this issue is closed in error please reopen!
