### ISSUE TITLE
Ability to convert Ember.Evented usage

### ISSUE THREAD

**Issue by mehulkar** [ember-lifeline/ember-lifeline#228]
Ability to replace `Ember.Evented` with an comparable API would be great. Example:

## Current
```js
// app/services/foo.js
import Evented from '@ember/object/evented';
export default Service.extend(Evented, {
  triggerEvent() {
    this.trigger('someEvent');
  }
});

// app/components/foo-bar.js
export default Component.extend({
  foo: service(),

  init() {
    this._super(...arguments);
    this.get('foo').on('someEvent', () => alert('called'))
  }
})
```

## Desired
I think a good way to do this would be to add `trigger` to the `ContextBoundEventListenersMixin`, so that it can be mixed into any object and can trigger events and register listeners.

```js
// app/services/foo.js
import { ContextBoundEventListenersMixin } from 'ember-lifeline';

export default Service.extend(ContextBoundEventListenersMixin, {
  triggerEvent() {
    this.trigger('someEvent');
  }
});

// app/components/foo-bar.js
import { addEventListener, runDisposables } from 'ember-lifeline';
export default EmberObject.extend({
  foo: service(),

  init() {
    this._super(...arguments);
    addEventListener(this, this.get('foo'), 'someEvent', () => alert('called'));
  }

  willDestroy() {
    runDisposables(this);
  }
})
```

Thoughts?

**Comment by mehulkar** [comment]
Or add a function like this:

/**
 * Ember Lifeline provides some primitives to dispose off event handlers bound to Ember.Evented
 * objects. This helper puts them together allowing the user to cleanly add and remove
 * listeners in the lifecycle of the listener.
 *
 * @function addEventedEventListener A helper to use ember-lifeline with Ember.Evented
 * @param {Object} listener The `this` context from where this is called
 * @param {Object} target The target that triggers the event name, that we want to listen to
 * @param {String} eventName The name of the event to bind the event handler to
 * @param {Function} handler A reference to the event handler
 */
export function addEventedEventListener(listener, target, eventName, handler) {
    const boundMethod = bind(listener, handler);
    target.on(eventName, boundMethod);
    registerDisposable(listener, () => target.off(eventName, boundMethod));
}

**Comment by mehulkar** [comment]
ping @scalvert @rwjblue

**Comment by scalvert** [comment]
Hey @mehulkar, thanks for opening this discussion. Sorry for the delay in getting back to you; I was delayed in responding while processing what this means/would look like.

I'm open to having _some_ API that we interact with that allows us to track usages of `Ember.Evented`'s APIs, but am not entirely sure what that should look like. I'm not convinced that we should overload the `addEventListener` implementation to work for both DOM and Evented events. This feels a bit odd to me, and I can't quite put my finger on why yet.

I'll start exploring what this could look like. Meanwhile, I'm curious what @rwjblue thinks.

**Comment by mehulkar** [comment]
Something explicit in the readme would be ok too. I think using registerDisposable is a fine way to convert usage.

**Comment by scalvert** [comment]
Just doing a bit of cleanup on issues in this repo. If this issue is closed in error please reopen!
