### ISSUE TITLE
[IE11] support for `{ once: true }`

### ISSUE THREAD

**Issue by buschtoens** [ember-lifeline/ember-lifeline#268]
IE11 does not natively support `{ once: true }`. While I am not using it, I think this is a crucial feature to support or, if not, at least explicitly document that it is not supported. Otherwise users will have a bad time when their app behaves differently in IE11.

Relates to #267, #266.

**Comment by scalvert** [comment]
Just doing a bit of cleanup on issues in this repo. If this issue is closed in error please reopen!
