### ISSUE TITLE
Loosen type from EmberObject to interface

### ISSUE THREAD

**Issue by scalvert** [ember-lifeline/ember-lifeline#288]
Currently, most of the functions provided require an `EmberObject` to be provided as a way to key the WeakMaps. We should loosen this type to be an interface that conforms to a specific shape of what we expect. This will help the move to using native classes.

**Comment by rwjblue** [comment]
I don't fully understand what you mean, are you just talking about the typings?

**Comment by scalvert** [comment]
Yes. Currently the type is EmberObject. I think it should be more loosely defined, even if just in name.

**Comment by rwjblue** [comment]
Gotcha. Yeah, I think defining the specific interface that we expect is important. _Especially_ as we approach custom components (ala sparkles-component / glimmer components) which vary quite a bit from Ember.Object.

**Comment by scalvert** [comment]
Agree.
