### ISSUE TITLE
assert.expect has unexpected behavior

### ISSUE THREAD

**Issue by mehulkar** [ember-lifeline/ember-lifeline#323]
Since ember-lifeline adds an assertion into `QUnit.testDone`, any user calls to `assert.expect` need to account for an extra assertion, which is weird. 

Maybe the assertion from the addon can be changed to a warning instead?

**Comment by scalvert** [comment]
Hey @mehulkar,

To clarify, you’re referring to the fact that you need to increment assert.expect to account for the extra assertion, correct? 

If so, we’ve done a similar thing in ember-qunit when pushing new assertions. We can do a similar thing here. It amounts to incrementing the test.expected property.

**Comment by mehulkar** [comment]
Yep that’s what I’m referring to.

Not sure how test.expected works, but I’m open to any solution! 

Just an ergonomics issue, really.

**Comment by scalvert** [comment]
Ya no worries. 

`test.expected` is just how QUnit internally manages the expected assertion count: https://github.com/qunitjs/qunit/blob/08f1c69210f1b0239d3f10a449998c7bdaa72d7f/src/assert.js#L58

In ember-qunit, when we push a new assertion, we increment the `test.expected` count here: https://github.com/emberjs/ember-qunit/blob/master/addon-test-support/ember-qunit/test-isolation-validation.js#L28.

I think we can just do the same here. I'll open a PR.

**Comment by mehulkar** [comment]
@scalvert were you able to look into this yet? I'm not quite sure what your comment means. I think the end goal is for ember-lifeline to NOT increment `test.expected` right?

**Comment by rwjblue** [comment]
We should change away from assert.deepEqual to throwing an error when the array is not empty. This would still properly fail the test, but not change the assertion count.
