### ISSUE TITLE
Document cancelPoll, cancelTask, etc

### ISSUE THREAD

**Issue by lolmaus** [ember-lifeline/ember-lifeline#35]
It took me quite a while to figure out that to cancel a poll I have to run both `cancelPoll` and `cancelTask`.

**Comment by mdebbar** [comment]
Now that you figured it out, would you mind sharing some code snippets and some explanation that can be added to the docs? Thank you!

**Comment by mdebbar** [comment]
Actually, on a second thought, I don't understand why we should be using `pollTask` at all. The docs say that nested `runTask` calls can cause acceptance tests to never complete. I understand that `setTimeout` and `run.later` could cause that issue, but I'm not sure how `runTask` could cause it.

When a component is destroyed, all the scheduled tasks are auto-cancelled, including the nested ones. That's guaranteed by ember-lifeline. @rwjblue could you elaborate more on why nested `runTask`s are problematic for acceptance tests?

**Comment by stefanpenner** [comment]
can a code-example be provided? I believe i see the issue, but want to make sure.

**Comment by mdebbar** [comment]
@stefanpenner the [`pollTask` section](https://github.com/rwjblue/ember-lifeline#polltask) in the README provides very good examples. I'm quoting from README:

======== START QUOTE ========

```js
import Component from 'ember-component';
import RunMixin from 'ember-lifeline/mixins/run';

export default Component.extend(RunMixin, {
  init() {
    this._super(...arguments);
    this.updateTime();
  },

  updateTime() {
    this.set('date', new Date());
    this.runTask(() => this.updateTime(), 20);
  }
});
```
However, more work is still needed since when used in an acceptance test, the snippet above will cause the test to never complete.

To avoid this testing "freezing" behavior, we would need to update the component to have different behavior when testing than when running in normal development / production. Typically, this is done something like:

```js
import Ember from 'ember';
import Component from 'ember-component';
import RunMixin from 'ember-lifeline/mixins/run';

export default Component.extend(RunMixin, {
  init() {
    this._super(...arguments);
    this.updateTime();
  },

  updateTime() {
    this.set('date', new Date());

    if (!Ember.testing) {
      this.runTask(() => this.updateTime(), 20);
    }
  }
});
```

======== END QUOTE ========

I'm still having trouble figuring out why the first code snippet is problematic in acceptance tests. If the "task" is auto-cancelled by ember-lifeline, where's the issue then?

**Comment by stefanpenner** [comment]
pollTask seems strange, my intuition suggests:

```
let token = this.pollTask(() => {
  return ajax(thing); // run this callback again, once the promise fulfills
}, time, label);

cancel(token); // cancel like any token
```

That gets rid of the strange nested next stuff, and also works nicely with async. Rather then the recursive call thingy.


@rwjblue / @scalvert would love your input as well.

**Comment by mdebbar** [comment]
@stefanpenner totally agree with you. The closer it is to the `setInterval` api, the better. Adding async support could be achieved as you suggested by returning a promise. At this point though, we probably want to keep `pollTask` backwards compatible and introduce a new method maybe?

**Comment by stefanpenner** [comment]
we can likely deprecate the existing behavior by checking the callbacks arity, if there is no arity do the new thing. Eventually (major version bump down the road) we can throw if the arity is wrong

**Comment by stefanpenner** [comment]
@rwjblue is on holidays. So I'm not sure when he will have time to provide feedback. But we may want to wait for it.

I do suspect he will be on-board with the above...

**Comment by stefanpenner** [comment]
Just chatting with @rwjblue. He is onboard.

**Comment by stefanpenner** [comment]
@mdebbar are  You interested in implementing? If not, I can handle it

**Comment by mdebbar** [comment]
I'll take care of it

**Comment by stefanpenner** [comment]
@mdebbar awesome, ping if you need review/release etc.

**Comment by dwickern** [comment]
👍 for the promise-style API. You'll have to decide whether to keep polling if a promise fails. Also the object might be destroyed by the time the promise resolves

**Comment by mdebbar** [comment]
> You'll have to decide whether to keep polling if a promise fails.

I'm leaning more towards keeping the polling even when the promise is rejected. We shouldn't care about the "semantics" of user's code. We are using the promise as an indication that the async work was completed so we can trigger the next "tick". Whether that async work fails or succeeds is none of our business. The user can always manually cancel the poll using `this.cancelPoll()` if they want to. Thoughts @stefanpenner @rwjblue ?

> Also the object might be destroyed by the time the promise resolves.

If the object is destroyed, the polling will be cancelled regardless of whether the promise is resolved later or not.

**Comment by rwjblue** [comment]
> You'll have to decide whether to keep polling if a promise fails.

IMHO, we should not automatically cancel the polling. It's easy enough to catch and cancel if that's actually what you wanted.

**Comment by lolmaus** [comment]
1.5 years later, `cancelTask` is not even mentioned in docs -- even though `cancelPoll` does *not* work without it.

**Comment by csprocket777** [comment]
I am still struggling with `cancelPoll`. I think I'm doing this correctly but it's not cancelling.

```
  setupSavePolling(){
    pollTask(this, 'saveUserProgressPollFunc', SAVE_POLL_TOKEN);
  },

  saveUserProgressPollFunc(next){
    this.saveUserProgress();
    set(this, 'SAVE_POLL_TASK', runTask(this, next, 30000));
  },

  async saveUserProgress(){
...
  },

  cancelSavePolling(){
    cancelPoll(this, SAVE_POLL_TOKEN);
    cancelTask(this, this.SAVE_POLL_TASK);
  },
```

**Comment by lolmaus** [comment]
Please reopen. The documentation mentions `cancelPoll` and `cancelTask` only briefly. It's not even clear which arguments these functions accept, not to mention the lack of a complete cancellation example.
