### ISSUE TITLE
After Ember 3.2 upgrade, didRender() hook in a component with poll is not fired appropriately in qunit tests

### ISSUE THREAD

**Issue by ajcolter** [ember-lifeline/ember-lifeline#358]
I have been using ember lifeline's pollTask to animate a sliding progress bar component because it provides the easiest test interface for testing the different steps. The component has 5 segments that animate over different lengths of time by applying different CSS styles. In my tests, I test that after each `pollTaskFor` the appropriate CSS class has been applied.

When I upgrade my app from Ember 3.1 to Ember 3.2, this test starts to fail. It sees that the 1st and 3rd classes are applied, but not for 2nd, 4th, or 5th (I implemented a workaround to wait for settledness for the last one). After digging in a bit more, I see that the 2nd and 4th classes are NOT applied before the assert is run in the test, and it seems to be because the `didRender()` hook on the component is not called after these polls, but it is called after the 3rd. I don't understand why it is called sometimes and not other times, and why this would have changed when going from Ember 3.1 to Ember 3.2.

I pulled out the progress bar component into its own Ember app, and the test failure is still occurring in QUnit. I also tried upgrading the sample app in incremental minor version steps all the way up to 3.8, and the test failures never resolved. When I reverted back to Ember 3.1, the tests passed again.

You can see this app and download it yourself here: https://github.com/ajcolter/ember-progress-bar
I left a few branches open for the different versions of Ember. The master branch is on 3.2

**Comment by scalvert** [comment]
Thanks for reporting, @ajcolter. I haven't observed this behavior myself, and I really appreciate the repro app.

I'll take a look at this ASAP.

**Comment by rwjblue** [comment]
Which specific test is failing in that app? Mind linking to it?

**Comment by rwjblue** [comment]
Also, for context Ember 3.2 includes a non-trivial version bump of the internal rendering engine. This is almost certainly the “why now?”, but we should still dig in to the specific failing test to see what’s going on and confirm there isn’t something we should be doing different...

**Comment by ajcolter** [comment]
@rwjblue I tried to keep the test files really pared down, this should be the only one (or one of two?) that run, and it is the one that is failing: https://github.com/ajcolter/ember-progress-bar/blob/master/tests/integration/components/progress-bar-test.js#L12

**Comment by rwjblue** [comment]
Thanks for the link! Sorry I was lazy and didn't look before asking...

One thing I notice is `await pollTaskFor(...)` usage in that test, and I wanted to point out that `pollTaskFor` does **not** return a promise or attempt to wait for async in any way. 
https://github.com/ember-lifeline/ember-lifeline/issues/39 is an issue for fixing that...

I'd add `await settled()` to your test just after calling `pollTaskFor`, I _believe_ that should fix the issue. Would you mind testing?

**Comment by ajcolter** [comment]
Adding `await settled()` does seem to fix it, thanks! That is definitely something I can do in my actual app, too. 
I do think the `pollTaskFor` documentation could be better (I'm not sure where I got the idea to `await` it), maybe that's something I could take a stab at.

**Comment by rwjblue** [comment]
Ya, and I'm also totally happy (now that @scalvert moved it to be a pure test-land helper) to add `return settled()` so that `await pollTaskFor(...)` directly "just works".

**Comment by scalvert** [comment]
Was gonna day the same thing! I can add it.
