### ISSUE TITLE
Maybe pollTaskFor should wait()?

### ISSUE THREAD

**Issue by dwickern** [ember-lifeline/ember-lifeline#39]
My tests fail if I don't `wait()` before and after `pollTaskFor`:
```js
await wait();
await pollTaskFor('label');
await wait();
```

The tests in this repo also seem to doing that. Any reason it can't be rolled into `pollTaskFor`?

**Comment by scalvert** [comment]
Hmmm, I wonder if we need to return `settled()` in that function.

```js
export function pollTaskFor(token) {
  assert(
    `You cannot advance pollTask '${token}' when \`next\` has not been called.`,
    !!queuedPollTasks[token]
  );

  run.join(null, queuedPollTasks[token]);

  return settled();
}
```

It'd be a bit weird to import test helpers stuff into prod code, but such is life when you expose testing functionality in a module.

@rwjblue - thoughts?

**Comment by rwjblue** [comment]
Seems "fine"ish...

**Comment by scalvert** [comment]
Unconvincing response...

**Comment by rwjblue** [comment]
hahaha, indeed!
