### ISSUE TITLE
Handling async functions/actions

### ISSUE THREAD

**Issue by knownasilya** [ember-lifeline/ember-lifeline#62]
Are there any ideas for handling lifecycles with async code beyond events and timeout stuff?

```js
async toggleDocuments() {
  let documents = this.get('documents');
  let show = this.toggleProperty('showDocuments');

  if (show && !documents) {
    let documents = await this.loadDocuments();

    // to not need this part
    if (this.isDestroyed || this.isDestroying) {
      return;
    }

    this.set('documents', documents);
  }
}
```

**Comment by scalvert** [comment]
It may be possible to do this by wrapping the method called and handling the `isDestroyed|isDestroying` logic within that wrapper. I'd have to think about how this would work and what the API would look like.

Interesting idea though!

**Comment by scalvert** [comment]
The direction we're headed is to keep the API surface area small. As such, it's unlikely we'd add any specific API to handle these types of use cases, particularly since they can be handled quite easily within app/addon code.
