### ISSUE TITLE
Watch / polyfill / update ongoing "destructors" RFC

### ISSUE THREAD

**Issue by rwjblue** [ember-lifeline/ember-lifeline#629]
Just creating this issue to remind us that we need to keep track of https://github.com/emberjs/rfcs/pull/580 as it progresses through the RFC process, and likely:

* create a dedicated polyfill addon (under ember-polyfills org)
* add that as a dependency, and update our internal destroyables implementation to leverage it

**Comment by scalvert** [comment]
Implemented in #852

**Comment by rwjblue** [comment]
🎉
