### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by rinoldsimon** [ember-lifeline/ember-lifeline#91]
After installing ember-lifeline in an Ember project, following error appears when running the server:

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
### Steps to Reproduce
In the Ember project install ember-lifeline:

> ember install ember-lifeline

After that run an Ember command like:

> ember -v

or:

> ember s

**Comment by scalvert** [comment]
As per @rwjblue's comment, we're not using babel 5.x.
