### ISSUE TITLE
Remove the use of WeakMap.clear due to its deprecation

### ISSUE THREAD

**Issue by scalvert** [ember-lifeline/ember-lifeline#98]
`WeakMap.clear` is [deprecated](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-19.md#412-should-weakmapweakset-have-a-clear-method-markm). It needs to be removed.

**Comment by rwjblue** [comment]
Where are we using `WeakMap.clear()`?

**Comment by scalvert** [comment]
False alarm. We're using `Set.clear` :)
